swagger: "2.0"
info:
  title: Task API
  version: "1.0"
  description: Simple Task API with Gin, GORM, PostgreSQL
basePath: /
host: localhost:8000
schemes: []
paths:
  /tasks:
    get:
      tags: [tasks]
      summary: Get all tasks
      description: Get list of tasks
      produces: [application/json]
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/models.Task'
    post:
      tags: [tasks]
      summary: Create a new task
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - in: body
          name: task
          description: Task Data
          required: true
          schema:
            $ref: '#/definitions/models.Task'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
  /tasks/{id}:
    put:
      tags: [tasks]
      summary: Update a task
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - in: path
          name: id
          description: Task ID
          required: true
          type: integer
        - in: body
          name: task
          description: Task Data
          required: true
          schema:
            $ref: '#/definitions/models.Task'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
    delete:
      tags: [tasks]
      summary: Delete a task
      parameters:
        - in: path
          name: id
          description: Task ID
          required: true
          type: integer
      responses:
        "200":
          description: OK
          schema:
            type: object
            additionalProperties:
              type: string
definitions:
  models.Task:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      completed:
        type: boolean
